[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aether-ml"
version = "0.1.0"
requires-python  = ">= 3.12"
dependencies = [
    "numpy", 
]

[project.optional-dependencies]
safetensors = ["safetensors>=0.8.0"]
gpu-nvidia = ["cupy-cuda12x"]   # CuPy wheel from PyPI
gpu-amd = []                    # CuPy compiled via ROCm container env

notebooks = [
    "safetensors>=0.8.0",
    "jupyterlab",
    "matplotlib",
]

dev = [
    "aether-ml[safetensors]",
    "aether-ml[notebooks]",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = [".env*", "tests*", "*.egg-info"]